config/routes.rb
KD::Application.routes.draw do

  resources :companies
  resources :locations
  resources :streams

  # namespace :payments do
  #   resources :customers do
  #     get 'client_token', on: :member
  #   end
  # end
  # get "/checkout", to: 'checkout#checkout', as: :checkout
  # get "/checkout/cr_card_confirm", to: 'checkout#cr_card_confirm', as: :cr_card_confirm
  # post "/checkout/set_tr", to: 'checkout#set_tr', as: :set_tr


  devise_for :partners, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :dispatches, only: [:index, :create]
  resources :notifications, only: [:index, :create]

  # get '/materials/:id', to: 'materials#share', as: :materials_share
  # get '/materials/download/:id', to: 'materials#download', as: :download_material

  # resource :shopping_cart, :only => [:show] do
  #   resources :items, only: [:create, :destroy], controller: :shopping_cart_items do
  #     get 'add_from_iframe', on: :collection, to: "shopping_cart_items#create"
  #   end
  #   get 'save_amount'
  # end

  devise_for :partners, :controllers => {
    :sessions => "partners/sessions",
    #:registrations => "partners/registrations",
    :passwords => "partners/passwords"
  }

  # resources :orders

  get "/partners/demo/buckscountyalive/", :to => "demonstrations#iframe_all_order", :as => "partner"
  get "/partners/demo/buckscountyalive/business/", :to => "demonstrations#iframe_business"
  get "/partners/business/list/", :to => "demonstrations#iframe_business_list"


  resources :stockphotos
  match '/photos/:category', :to => 'stockphotos#category'
  match '/photos', :to => 'stockphotos#category'

  mount Attachinary::Engine => "/attachinary"

  ensure_admin = lambda do |request|
    request.env['warden'].authenticated?(:merchant) and request.env['warden'].user(:merchant).is_admin?
  end

  constraints ensure_admin do
    mount Resque::Server, at: "/resque/web"
    #mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

    namespace :admin do
      root :to => "consumers#index"
      get 'data' => 'charts#data'
      resources :consumers, :businesses, :campaigns, :referrals, :partners
      resources :merchants do
        get 'campaign_stats/:campaign_id' => 'merchants#campaign_stats'
      end
    end
  end

  Devise.router_name = :main_app

  match '/category/all-offers/philadelphia/:tag', :to => 'categories#show', :as => :categories_show
  match '/category/all-offers', :to => 'categories#show_all', :as => :categories_show_all
  match '/category/partner/:slug', :to => 'categories#show_partner', :as => :categories_show_partner

  get "/businesses/:id/offers", :to => "categories#show_all", :as => :categories_show_business_all
  match '/businesses/examples', :to => 'businesses#examples'
  match '/businesses/list', :to => 'categories#business_list'

  devise_for :consumers, :controllers => {
    :sessions => "consumers/sessions",
    :registrations => "consumers/registrations",
    :passwords => "consumers/passwords",
    :omniauth_callbacks => "consumers/omniauth_callbacks"
  }

  devise_for :merchants, :controllers => {
    :sessions => "merchants/sessions",
    :registrations => "merchants/registrations",
    :passwords => "merchants/passwords"
  }

  # controller :coupons do
  #   get '/coupons' => 'coupons#index'
  # end

  namespace :merchants do
    resource :contact_us, :only => ["new", "create"]
    resources :companies
    resources :locations, :except => ["index", "show"]
    resources :streams, :except => ["index", "show"]
  end


  namespace :consumers do
    controller :application  do
      get '/login', :action => 'login', :as => 'consumerlogin'
      get '/signup_form', :action => 'signup_form', :as => 'signup_form'
    end

    controller :dashboard  do
      get '/dashboard' => 'dashboard#index'
      get '/dashboard' => 'dashboard#index'
      get '/directions' => 'dashboard#directions'
    end

    # controller :picks do
    #   get '/offers' => 'picks#index', :as => 'offers'
    #   get '/offers/subscribe' => 'picks#subscribe'
    #   get '/offers/myhotspots' => 'picks#myhotspots'
    #   get '/offers/for_business/:id' => 'picks#for_business'
    #   get '/offers/:id' => 'picks#show', as: 'show_offer'
    # end

    resources :businesses, :only => [:index, :show] do
      member do
        post 'toggle_subscription' => 'businesses#toggle_subscription'
        #get 'toggle_subscription' => 'businesses#toggle_subscription'
      end
    end

    resources :locations

    controller :mobile_confirmations do
      get '/mobile/view', :action => 'view', :as => 'send_mobile_confirmation_token'
      get '/mobile/confirm/:confirmation_code', :action => 'confirm', :as => 'mobile_confirmation'
      post '/mobile/confirm', :action => 'confirm', :as => 'mobile_confirmation'
    end
  end

  resource :consumer, :controller => "consumers/consumer" do
    post :update_location, :action => 'update_location', :on => :collection
    # get :toggle_email_weekly
    # post :toggle_email_weekly
    # get :confirm_email
    # get :buy_coupon
    # post :buy_coupon
    # get :transactions
    # get :coupon_purchase_status
    get :complete_registration


  end

  resources :customer, :only => [:new, :edit]
  # resources :credit_card_info, :only => [:new, :edit, :destroy]
  # match '/credit_card_info/:id/set_default' => 'credit_card_info#set_default', :as => :set_default_credit_card

  #get "/credit_card_info/edit_default", to: 'credit_card_info#edit_default', as: :edit_default_credit_card_info

  match 'customer/confirm' => 'customer#confirm', :as => :confirm_customer
  # match 'credit_card_info/confirm' => 'credit_card_info#confirm', :as => :confirm_credit_card_info

  # match '/consumers/transactions/new' => 'transactions#new', :as => :new_transaction
  # match '/consumers/transactions/new_paypal' => 'transactions#new_paypal', :as => :new_paypal_transaction
  # match '/consumers/transactions/:id/show' => 'consumers/consumer#show_transaction', :as => :show_transaction
  # match '/consumers/transactions/confirm/' => 'transactions#confirm', :as => :confirm_transaction
  # match '/consumers/transactions/confirm_paypal/' => 'transactions#confirm_paypal', :as => :confirm_paypal_transaction

  # match '/consumers/receipts/:id/show' => 'consumers/consumer#show_receipt', :as => :show_receipt


  post "/set_current_business" => "merchants/application#set_current_business"

  get '/merchants/login' => 'merchants/application#login'
  match '/business/:id/upload_image' => 'businesses#upload_image', :as => :upload_business_image
  match '/business/:id/images' => 'businesses#images', :as => :business_images
  match '/business/:id/add_images' => 'businesses#add_images', :as => :business_add_images

  resources :businesses do

    collection do
      get 'activation'
      post 'activation'
      get 'redeem'
    end

    member do
      get 'oauth_connect'
      get 'oauth_callback'
      get 'facebook_oauth_connect'
      get 'facebook_oauth_callback'
      get 'reset_social'
    end
  end

  resource :account do
    collection do
      post :upgrade
    end
  end

  # resources :campaigns do
  #   member do
  #     get :recipient_demographics
  #     get :statistics
  #     get :campaign_data
  #     get :sales
  #   end
  #   collection do
  #     match :count_recipients
  #     get :scheduled
  #     get :delivered
  #   end
  # end

  resources :companies, only: [:index, :show]

  # get '/pages/dollarhood_for_business/' => "pages#dollarhood_for_business", :as => "page_business"
  match '/pages/:action', :controller => "pages", :as => "pages"
  root :to => 'companies#index'

  controller :dashboard do
    get '/dashboard' => 'dashboard#index'
    get '/dashboard/demographics/:group' => 'dashboard#demographics'
  end

  # match '/coupons/redeem'    => "coupons#redeem",  :as => "redeem_coupon", :via => [:get, :post]
  # get   '/coupons/preview'   => "coupons#preview"
  # post  '/coupons/hook'      => "coupons#hook"
  # get   '/coupons/:code'     => "coupons#view",    :as => "view_coupon"
  # get   '/coupons_json/:code' => "coupons#view_json", :as => 'view_coupon_json'

  resource :contact_us, :only => ["new", "create"]
  match '*a', :to => 'errors#error_404'
  #get '/businesses/croplogo/:id' => 'businesses#crop'
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :title, :description

  has_many :locations
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :merchants

	validates :title, presence: true, uniqueness: true
	validates :description, presence: true

  has_attachment :avatar, accept: [:jpg, :png, :gif, :svg]
end

app/controllers/businesses_controller.rb
class BusinessesController < Merchants::ApplicationController
  before_filter :authenticate_merchant!, :except => %w[list]
  before_filter :get_business, :except => %w[index new create examples list]

  def index
    @businesses = current_merchant.businesses.all
  end

  def new
    @business = Business.new
    @twitter_client = TwitterClient.new(@business.access_token,
                                        @business.secret_token)
  end

  def create
    @business = current_merchant.businesses.new(params[:business])
    if @business.save
      flash[:success] = "Created #{@business.name}!"
      redirect_to businesses_path
    else
      flash[:error] = "Failed to create business"
      render :new
    end
  end

  def reset_social
    account = params[:account].to_sym
    business = Business.find(params[:id])

    case account
    when :facebook
      business.reset_facebook_credentials
      business.save!

    when :facebook_page
      business.reset_facebook_page
      business.save!

    when :twitter
      business.reset_twitter_credentials
      business.save!

    end

    redirect_to edit_business_path(business)
  end

  def examples

  end

  def crop
    @business = Business.find(params[:id])
  end

  def edit
    logger.debug 'welcome: ' + params.has_key?(:welcome).to_s
    @twitter_client = TwitterClient.new(@business.access_token,
                                        @business.secret_token)
  end

  def update
    if @business.update_attributes(params[:business])
      redirect_to edit_business_path(@business) , :flash => { :success => "Profile complete", :money => true }
    else
      flash[:error] = "Failed to save profile"
      render :edit
    end
  end

  def upload_image
    if @business.update_attributes(params[:business])
      redirect_to new_campaign_path('business_images' => true) , :flash => { :success => "Image uploaded" }
    else
      redirect_to new_campaign_path('business_images' => true) , :flash => { :error => "Failed to save profile" }
    end
  end

  def images
    render :layout => false
  end

  def add_images
    render :layout => 'bare'
  end

  def facebook_oauth_connect
    callback_url = facebook_oauth_callback_business_url(@business)
    redirect_to @business.facebook_client(callback_url).authorization_uri(:scope => [:offline_access, :manage_pages, :publish_stream, :publish_actions])
  end

  def facebook_oauth_callback
    begin
      callback_url = facebook_oauth_callback_business_url(@business)
      @business.facebook_client(callback_url).authorization_code = params[:code]
      authorization = @business.facebook_client.access_token! :client_auth_body # => Rack::OAuth2::AccessToken::Legacy
      @business.facebook_access_token = authorization.access_token
    rescue Exception => e
      flash[:error] = "Could not authorize Facebook: #{e.response.inspect}"
    end

    if @business.facebook_client_authorized?
      flash[:success] = "Successfully authorized Facebook!"
      @business.save
    end
    redirect_to edit_business_path(@business)
  end

  def oauth_connect
    callback_url = oauth_callback_business_url(@business)
    request_token = TwitterLink.request_token(callback_url)
    session[:request_token] = request_token.token
    session[:request_token_secret] = request_token.secret
    redirect_to request_token.authorize_url
  end

  def oauth_callback
    link = TwitterLink.new(session[:request_token],
                           session[:request_token_secret],
                           params[:oauth_verifier])

    if link.authorized?
      @business.access_token = link.access_token.token
      @business.secret_token = link.access_token.secret
      @business.save
      flash[:success] = "Successfully authorized Twitter!"
    else
      flash[:error] = "Failed to authorize to twitter"
    end

    redirect_to edit_business_path(@business)
  end

  private

  def get_business
    @business = current_merchant.businesses.find(params[:id]) rescue nil
  end

end

app/controllers/consumers/businesses_controller.rb
class Consumers::BusinessesController < Consumers::ApplicationController

  before_filter :get_categories, except: %w[toggle_subscription show]

  add_breadcrumb "Businesses", :consumers_businesses_path

  def index
    @businesses = Business.near(current_consumer.location, 100)
    @businesses = filter_by_subscription_type(params[:subscription_filter], @businesses)
    @businesses = filter_by_business_name(params[:business_name], @businesses)
    @businesses = filter_by_category(@category, @businesses)
  end

  def show
    @business = Business.find(params[:id])
    @campaigns = @business.campaigns.where(:state => 'delivered')

    @all_businesses = @business.merchant.businesses.where('id != ?', @business.id).where(:state => 'delivered')
  end

  def toggle_subscription
    @business = Business.find(params[:id])
    puts "Toggle subscription test"
    puts "current consumer subscribed? - #{current_consumer.subscribed_to?(@business)}"
    puts "subscribers count - #{@business.subscribers.count}"
    if current_consumer.subscribed_to?(@business)
      @business.subscribers.delete(current_consumer)
    else
      @business.subscribers << current_consumer
    end
    puts "subscribers count - #{@business.subscribers.count}"

    respond_to do |format|
      format.html { render :nothing => true }
      format.mobile { redirect_to consumers_businesses_path }
      format.js
      format.json
    end
  end

  private
    def get_categories
      @category = Category.find_by_id(params[:category_id])
      @categories = Category.for_grouped_select
    end

    def filter_by_subscription_type(subscription_type, collection = Business.all)
      case subscription_type
      when 'subscribed'
        collection.select {|b| current_consumer.favorites.include?(b) }
      when 'not_subscribed'
        collection.select {|b| !current_consumer.favorites.include?(b) }
      else
        collection
      end
    end

    def filter_by_business_name(business_name, collection = Business.all)
      return collection if business_name.blank?
      collection.select {|b| b.name =~ /^#{business_name}/ }
    end

    def filter_by_category(category, collection = Business.all)
      return collection if category.nil?
      collection.select {|b| b.categories.include?(category) }
    end

end

app/views/businesses/_categories_selector.html.haml
%p.header= f.label "Categorize your business to reach new customers interested in types of goods/services you provide!"
%br
%p Make sure you select a category that most reflects your business’s offer.  Your offer will appear on the main Offer Board and again when a customer narrows their search by category.
%br
.group
  - @cats = Category.top_level.in_groups(2, false)
  .col_a 
    - @cats[0].each do |category|
      %div.row
        = f.check_box :category_ids, {:multiple => true}, category.id, nil
        = category.name
  .col_b
    - @cats[1].each do |category|
      %div.row
        = f.check_box :category_ids, {:multiple => true}, category.id, nil
        = category.name

app/views/businesses/_configure_social_apis.html.haml
%p.header Social Networks
%br
- if @business.new_record?
  Not yet configured.
- else
  .twitter-oauth
    %h3 Twitter
    - if @business.has_twitter_credentials?
      - if @twitter_client.authorized?
        %p
          You may post a coupon to
          = link_to "@#{@twitter_client.screen_name}", "https://twitter.com/#{@twitter_client.screen_name}"
      - else
        %p
          Linked!
      = link_to 'Unlink', reset_social_business_url(:account => 'twitter'), :confirm => 'Are you sure?'
    - else
      %p
        Not yet configured.
        = link_to 'Configure', oauth_connect_business_url(@business)
  %br

  .facebook-oauth
    %h3 Facebook
    - if @business.facebook_client_authorized?
      - if @business.facebook_page_authorized?
        %p
          You may post a coupon to the
          = link_to @business.facebook_page_name, "https://facebook.com/#{@business.facebook_page.identifier}"
          facebook page
        %p
          = link_to 'Choose another page', reset_social_business_url(:account => 'facebook_page'), :confirm => 'Are you sure?'
      - else
        %p
          - if @business.facebook_user.accounts.size > 0
            Choose a page for #{@business}
            = form_for @business do |f|
              - @business.facebook_user.accounts.each do |fb_account|
                %p
                  = f.radio_button :facebook_page_identifier, fb_account.identifier
                  = fb_account.name
          - else
            You do not have any Facebook page associated with your facebook account.
            You can create one
            %a(href="http://www.facebook.com/pages/create.php") here.
      %p
        = link_to 'Unlink', reset_social_business_url(:account => 'facebook'), :confirm => 'Are you sure?'
    - else
      %p
        Not yet configured.
        = link_to 'Configure', facebook_oauth_connect_business_url(@business)

app/views/businesses/_form.html.haml
= render 'validation_errors', resource: @business
%br/
%p.header= f.label :logo, 'Upload Your Company Logo'
%p.form
- if @business.logo
  - logostr = "v#{@business.logo.version}/#{@business.logo.public_id}"
  = cl_image_tag(logostr, { size: '90x85', crop: :fit, format: :jpg })
- else
  = image_tag('default_business_logo.png')
= f.attachinary_file_field :logo
%br/
= render :partial => "businesses/categories_selector", :locals => {:f => f}

%p.header= f.label :name
%p.form= f.text_field :name
%p.header
  = f.check_box :online_business
  = f.label :online_business

%div{:class => 'promocode_field', :style => @business.online_business == 1.to_s ? 'display: none' : ''}
  %p.header= f.label :address
  %p.form= f.text_field :address
  %p.header= f.label :city
  %p.form= f.text_field :city
  %p.header= f.label :state
  %p.form= f.subregion_select :state, Carmen::Country.coded('us'), :prompt => "Select State *"


%p.header= f.label :zip_code
%p.form= f.text_field :zip_code
%p.header= f.label :phone
%p.form= f.text_field :phone
%p.header= f.label :web_site
%p.form= f.text_field :website
%p.header= f.label :description, 'Business Description'
%p.form= f.text_area :description, :rows => 6, :placeholder => "A few sentences to inform consumers about your business."
=render partial: 'businesses/configure_social_apis'

app/views/businesses/_images.html.haml
.jcarousel
  %ul
    - unless @business.images.nil?
      - @business.images.each do |image|
        %li
          %a.img
            - logostr = "v#{image.version}/#{image.public_id}"
            = cl_image_tag(logostr, { size: '240x160', crop: :fill, format: :jpg })
:css
  a.img IMG {
    height:80px;
    width:120px;
  }
:javascript
  jQuery(function($){
    function select() {
      var imgSrcVal = $('img', this).attr("src");
      $('#campaign_coupon_attributes_thumb').val(imgSrcVal); // hidden
      $('#campaign_coupon_attributes_subject').change(); // trigger update
      $('#results').html('');
    }
    $('a.img').on("click", select);
  });

app/views/businesses/add_images.html.haml
= form_for @business, url: upload_business_image_path(@business), :html => {:multipart => true} do |b|
  %br/
  %br/
  = b.label :images, "Upload your own photo:"
  = b.attachinary_file_field :images, input_html: { multiple: true } 

  %a.click-to-browse
    Click to Browse
  %br/
  %br/
  = b.submit "Save Image", class: 'btn btn-primary'

app/views/businesses/crop.html.haml
%h2 Crop the region which will be used as a logo
%br

= stylesheet_link_tag "3rd_partyjquery.Jcrop.min"
= javascript_include_tag "3rd_party/jquery.Jcrop.min"

= form_for @business do |f|
  - for attribute in [:crop_x, :crop_y, :crop_w, :crop_h]
    = f.hidden_field attribute, :id => attribute

  %br
  = f.submit "Crop"

:javascript
  var updateCrop = function (box) {
    var ratio = #{@business.logo_geometry(:original).width / @business.logo_geometry(:full).width}
    $('#crop_x').val(Math.floor(box.x * ratio))
    $('#crop_y').val(Math.floor(box.y * ratio))
    $('#crop_w').val(Math.floor(box.w * ratio))
    $('#crop_h').val(Math.floor(box.h * ratio))
  }

  $('#cropbox').Jcrop({
    onChange: updateCrop,
    onSelect: updateCrop,
    setSelect: [0,0,100,100],
    aspectRatio: 1
  })

%br

app/views/businesses/edit.html.haml
= render partial: 'popups/welcome' if flash.key?(:welcome)
= render partial: 'popups/make_some_money' if flash.key?(:money)
- if nil != @shown
  - flash.each do |key, message|
    .alert-message{:class => key}
      = message

- smart_path = @admin_edit ? admin_business_path(@business) : business_path(@business)
= form_for @business, :url => smart_path, :html => {:multipart => true, :class => "split-2"} do |f|
  .group
    .column1
      %h1 Business Profile
      = render :partial => 'businesses/form', :locals => {:f => f}
      .clear
      = f.submit "Save", class: 'special'

app/views/businesses/examples.html.haml
= image_tag('business-offer-examples.png')

app/views/businesses/images.html.haml
= render :partial => 'images'

app/views/businesses/index.html.haml
.group.business
  %h1 My Businesses
  .group
    - @businesses.each do |business|
      .business.row
        .business-image
          - if business.logo
            - logostr = "v#{business.logo.version}/#{business.logo.public_id}"
            = link_to cl_image_tag(logostr, { size: '90x85', crop: :fit, format: :jpg }), edit_business_path(business)
          - else
            = link_to image_tag('default_business_logo.png', :width => '100'), edit_business_path(business)
        .business-name
          %p
            = link_to business.name, edit_business_path(business)
            %br/
            %br/
          %p
            = business.full_address
  .row
    = button_to "+ Add A Business", new_business_path, :method => :get, class: 'add_business'

app/views/businesses/new.html.haml
- smart_path = @admin_edit ? admin_businesses_path : businesses_path
= form_for @business, url: smart_path, :html => {:multipart => true} do |f|
  .group
    .column1
      %h1 New Business Profile
      = render :partial => 'businesses/form', :locals => {:f => f}
      = f.submit "Add Business", class: 'special' 

app/views/businesses/redeem.html.haml
%div(style="width: 70%; margin-left: 15%; margin-top: 5%")
  %h1
    - if @b
      %p= @b.name + ', '
    %p= @message
    %br
    %p Please press scan button above to continue...
    %br
    %p Thank you.

app/views/businesses/redeem.mobile.html.haml
%div(style="width: 70%; margin-left: 15%; margin-top: 5%")
  %h1
    - if @b
      %p= @b.name + ', '
    %p= @message
    %br
    %p Please press scan button above to continue...
    %br
    %p Thank you.